apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: express-demo
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./nodejs/kustomize
  prune: true
  sourceRef:
    kind: GitRepository
    name: express-demo
  targetNamespace: default