apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: fastapi-demo
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./python/kustomize
  prune: true
  sourceRef:
    kind: GitRepository
    name: fastapi-demo
  targetNamespace: default